apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../infrastructure/sources
  - ../../infrastructure/ingress-nginx
  - ../../infrastructure/cert-manager
  - ../../infrastructure/rancher
patchesStrategicMerge:
  - rancher-values.yaml
