---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
      version: 2.5.7
  interval: 5m
  releaseName: rancher-server
  values:
    hostname: rancher.topgolf.com
