---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
      version: 2.5.7
  dependsOn:
    - name: cert-manager
  interval: 1h0m0s
  values:
    hostname: rancher.topgolf.com
